### ISSUE TITLE
v5.5.2: NullPointerException arising from NcML when accessed via OPeNDAP

### ISSUE THREAD

**Issue by zequihg50** [Unidata/netcdf-java#1028]
### Versions impacted by the bug

v5.x

### What went wrong?

When serving a simple NcML through OPeNDAP in the TDS, a NullPointerException arises from netCDF-java. This is caused by [MFileProvider.java](https://github.com/Unidata/netcdf-java/blob/53eaf4a968c86330bbde2e1b767588ab57b6c09d/cdm/core/src/main/java/thredds/inventory/MFileProvider.java#L21) checking a null `location` from an empty `<netcdf>` element in the NcML. Example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
    <aggregation type="union">
        <netcdf>
            <aggregation type="union">
		    <netcdf location="2004050400_eta_211.nc" /> <!-- from public/testdata -->
            </aggregation>
        </netcdf>
    </aggregation>
</netcdf>
```
If `false` is returned from MFileProvider when location is null, it appears to work.

### Relevant stack trace

```shell
java.lang.NullPointerException: null
	at thredds.inventory.MFileProvider.canProvide(MFileProvider.java:21) ~[main/:?]
	at thredds.inventory.MFiles.create(MFiles.java:37) ~[main/:?]
	at ucar.nc2.internal.ncml.AggDataset.<init>(AggDataset.java:74) ~[main/:?]
	at ucar.nc2.internal.ncml.Aggregation.makeDataset(Aggregation.java:453) ~[main/:?]
	at ucar.nc2.internal.ncml.Aggregation.addExplicitDataset(Aggregation.java:136) ~[main/:?]
	at ucar.nc2.internal.ncml.NcmlReader.readAgg(NcmlReader.java:1476) ~[main/:?]
	at ucar.nc2.internal.ncml.NcmlReader.readNetcdf(NcmlReader.java:521) ~[main/:?]
	at ucar.nc2.internal.ncml.NcmlReader.readNcml(NcmlReader.java:478) ~[main/:?]
	at ucar.nc2.internal.ncml.NcmlReader.readNcml(NcmlReader.java:397) ~[main/:?]
	at ucar.nc2.internal.ncml.NcmlNetcdfFileProvider.open(NcmlNetcdfFileProvider.java:24) ~[main/:?]
	at ucar.nc2.dataset.NetcdfDatasets.openProtocolOrFile(NetcdfDatasets.java:431) ~[main/:?]
	at ucar.nc2.dataset.NetcdfDatasets.openFile(NetcdfDatasets.java:347) ~[main/:?]
	at ucar.nc2.dataset.NetcdfDatasets$StandardFileFactory.open(NetcdfDatasets.java:38) ~[main/:?]
	at ucar.nc2.dataset.NetcdfDatasets$StandardFileFactory.open(NetcdfDatasets.java:35) ~[main/:?]
	at ucar.nc2.util.cache.FileCache.acquire(FileCache.java:267) ~[main/:?]
	at ucar.nc2.dataset.NetcdfDatasets.openOrAcquireFile(NetcdfDatasets.java:409) ~[main/:?]
	at ucar.nc2.dataset.NetcdfDatasets.acquireFile(NetcdfDatasets.java:386) ~[main/:?]
	at ucar.nc2.dataset.NetcdfDatasets.acquireFile(NetcdfDatasets.java:361) ~[main/:?]
	at thredds.core.DatasetManager.openNetcdfFile(DatasetManager.java:245) ~[main/:?]
	at thredds.core.TdsRequestedDataset.openAsNetcdfFile(TdsRequestedDataset.java:162) ~[main/:?]
	at thredds.core.TdsRequestedDataset.getNetcdfFile(TdsRequestedDataset.java:89) ~[main/:?]
	at thredds.server.opendap.OpendapServlet.getDataset(OpendapServlet.java:957) ~[main/:?]
	at thredds.server.opendap.OpendapServlet.doGetHTML(OpendapServlet.java:616) ~[main/:?]
	at thredds.server.opendap.OpendapServlet.doGet(OpendapServlet.java:199) [main/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) [spring-web-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) [spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.12.jar:5.3.12]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.12.jar:5.3.12]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.12.jar:5.3.12]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.79]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.79]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.79]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.79]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.4.7.jar:5.4.7]
	at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:50) [main/:?]
	at org.springframework.security.web.FilterChainProxy$V(base)
```

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

N/A

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by tdrwenski** [comment]
Hello,

Thanks for reporting this bug! We actually have already fixed this bug in the latest snapshot (https://github.com/Unidata/netcdf-java/pull/1019 -- just like you said, by returning false if the location is null) and hope to have a release out soon with this fix.

Best,
Tara
