### ISSUE TITLE
[VERSION]: 5.5.2 Dimension length =0 must be > 0

### ISSUE THREAD

**Issue by deepikm** [Unidata/netcdf-java#1037]
### Versions impacted by the bug

v5.x

### What went wrong?

Unable to open hdf5 file which fails with error: `Dimension length =0 must be > 0`. 

The same file works fine when using the deprecated `NetcdfFile.open(...)` instead of newer `NetcdfFiles.open(...)`. The deprecated function, logs error but continues to read the file successfully. Error Logged:
`DEBUG ucar.nc2.NetcdfFile - Using IOSP ucar.nc2.iosp.hdf5.H5iosp
ERROR ucar.nc2.iosp.hdf5.H5header - shape[0]=0 must be > 0
DEBUG ucar.nc2.iosp.hdf5.H5header - ERROR: makeVariableShapeAndType shape[0]=0 must be > 0` 

Given our scenario, we are not processing the variables that causes the issue, hence we would like to continue reading the file ignoring the error. The hdf5 files we use for processing are from our external partners. 

Is it possible to have the same behavior of ignoring the error be added to new implementation as well? It comes down to the H5Header.java -> makeVariableShapeAndType -> which has a try/catch that handles the InvalidRangeException whereas in new implementation, its thrown as Runtime - IllegalArgumentException. 

### Relevant stack trace

```shell
Caused by: java.io.IOException: java.lang.IllegalArgumentException: 
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:279)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:243)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:216)
	... 33 more
Caused by: java.lang.IllegalArgumentException: Dimension length =0 must be > 0
	at ucar.nc2.Dimension$Builder.setLength(Dimension.java:582)
	at ucar.nc2.Dimensions.makeDimensionsAnon(Dimensions.java:141)
	at ucar.nc2.Variable$Builder.setDimensionsAnonymous(Variable.java:2061)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.makeVariableShapeAndType(H5headerNew.java:1565)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.makeVariable(H5headerNew.java:1326)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.makeNetcdfGroup(H5headerNew.java:549)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.makeNetcdfGroup(H5headerNew.java:539)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.makeNetcdfGroup(H5headerNew.java:539)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.makeNetcdfGroup(H5headerNew.java:539)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.makeNetcdfGroup(H5headerNew.java:539)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.read(H5headerNew.java:264)
	at ucar.nc2.internal.iosp.hdf5.H5iospNew.build(H5iospNew.java:122)
	at ucar.nc2.NetcdfFiles.build(NetcdfFiles.java:811)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:750)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:276)
	... 36 more
```

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

No

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by mnlerman** [comment]
Hi @deepikm! I'm working on resolving this bug. Do you have a file you could provide for testing?
