### ISSUE TITLE
GDAS data decode

### ISSUE THREAD

**Issue by zfy68** [Unidata/netcdf-java#1079]
### Discussed in https://github.com/Unidata/netcdf-java/discussions/1078

<div type='discussions-op-text'>

<sup>Originally posted by **zfy68** September  4, 2022</sup>
### Question
I want read  gdas data , example `gdas.t00z.1bamua.tm00.bufr_d`, i use local code start `ucar.nc2.ui.ToolsUI` ,some exception.

![this is error info](https://user-images.githubusercontent.com/37278360/188278489-e2f3b30f-dc9b-443a-b2a1-e1831b05f9a3.png)

sourcode exception as follows :
```
java.io.IOException: java.lang.IllegalArgumentException: Type is Sequence, must be String or char
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:279)
	at ucar.nc2.dataset.NetcdfDatasets.openProtocolOrFile(NetcdfDatasets.java:455)
	at ucar.nc2.dataset.NetcdfDatasets.openFile(NetcdfDatasets.java:347)
	at ucar.nc2.dataset.NetcdfDatasets$StandardFileFactory.open(NetcdfDatasets.java:38)
	at ucar.nc2.dataset.NetcdfDatasets$StandardFileFactory.open(NetcdfDatasets.java:35)
	at ucar.nc2.dataset.NetcdfDatasets.openOrAcquireFile(NetcdfDatasets.java:413)
	at ucar.nc2.dataset.NetcdfDatasets.acquireFile(NetcdfDatasets.java:386)
	at ucar.nc2.dataset.NetcdfDatasets.acquireFile(NetcdfDatasets.java:361)
	at ucar.nc2.ui.ToolsUI.openFile(ToolsUI.java:1228)
	at ucar.nc2.ui.op.DatasetViewerPanel.process(DatasetViewerPanel.java:89)
	at ucar.nc2.ui.OpPanel.doit(OpPanel.java:161)
	at ucar.nc2.ui.OpPanel.lambda$new$0(OpPanel.java:74)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at ucar.ui.prefs.ComboBox.fireActionEvent(ComboBox.java:160)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
	at ucar.nc2.ui.OpPanel$2.actionPerformed(OpPanel.java:100)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Type is Sequence, must be String or char
	at ucar.ma2.ArrayStructureBB.getScalarString(ArrayStructureBB.java:410)
	at ucar.ma2.StructureDataA.getScalarString(StructureDataA.java:187)
	at ucar.nc2.iosp.bufr.EmbeddedTable.addTableEntryB(EmbeddedTable.java:108)
	at ucar.nc2.iosp.bufr.EmbeddedTable.add(EmbeddedTable.java:88)
	at ucar.nc2.iosp.bufr.EmbeddedTable.read2(EmbeddedTable.java:74)
	at ucar.nc2.iosp.bufr.EmbeddedTable.getTableLookup(EmbeddedTable.java:256)
	at ucar.nc2.iosp.bufr.MessageScanner.next(MessageScanner.java:182)
	at ucar.nc2.iosp.bufr.MessageScanner.getFirstDataMessage(MessageScanner.java:73)
	at ucar.nc2.iosp.bufr.BufrIosp2.build(BufrIosp2.java:79)
	at ucar.nc2.NetcdfFiles.build(NetcdfFiles.java:811)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:750)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:276)
	... 52 more

```
Excuse me, what is the reason for this?

### refer to :
[gdas data download ](https://www.ncei.noaa.gov/products/weather-climate-models/global-data-assimilation)
</div>

**Comment by shahramn** [comment]
Looks like PrepBUFR format

**Comment by zfy68** [comment]
> Looks like PrepBUFR format
is.
![image](https://user-images.githubusercontent.com/37278360/188293349-f1f01f62-af17-41f6-822b-4df1ec0cbfea.png)

**Comment by zfy68** [comment]
thanks，i already resolved.
