### ISSUE TITLE
cdmremote fails on https: URL

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#120]
works:
http://thredds.ucar.edu/thredds/cdmremote/grib/NCEP/GFS/Pacific_20km/GFS_Pacific_20km_20190918_1200.grib2

fails:
https://thredds.ucar.edu/thredds/cdmremote/grib/NCEP/GFS/Pacific_20km/GFS_Pacific_20km_20190918_1200.grib2

error message:
ucar.httpservices.HTTPException: java.net.URISyntaxException: Expected scheme-specific part at index 5: HTTP:
	at ucar.httpservices.HTTPAuthUtil.authscopeToURI(HTTPAuthUtil.java:112)
	at ucar.httpservices.HTTPSession.init(HTTPSession.java:811)
	at ucar.httpservices.HTTPSession.<init>(HTTPSession.java:797)
	at ucar.httpservices.HTTPFactory.newSession(HTTPFactory.java:38)
	at ucar.nc2.stream.CdmRemote.<init>(CdmRemote.java:79)
	at ucar.nc2.stream.CdmRemoteNetcdfFileProvider.open(CdmRemoteNetcdfFileProvider.java:19)
	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:712)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:430)
	at ucar.nc2.dataset.NetcdfDataset.acquireDataset(NetcdfDataset.java:576)
	at ucar.nc2.dataset.NetcdfDataset.acquireDataset(NetcdfDataset.java:536)
	at ucar.nc2.ui.ToolsUI.openFile(ToolsUI.java:1271)
	at ucar.nc2.ui.op.DatasetViewerPanel.process(DatasetViewerPanel.java:98)
	at ucar.nc2.ui.OpPanel.doit(OpPanel.java:173)
	at ucar.nc2.ui.OpPanel.lambda$new$0(OpPanel.java:83)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at ucar.ui.prefs.ComboBox.fireActionEvent(ComboBox.java:160)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
	at javax.swing.plaf.basic.BasicComboBoxUI$Handler.actionPerformed(BasicComboBoxUI.java:1943)
	at javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
	at javax.swing.JTextField.postActionEvent(JTextField.java:721)
	at javax.swing.JTextField$NotifyAction.actionPerformed(JTextField.java:836)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by lesserwhirls** [comment]
@DennisHeimbigner - here is another `httpservices` related issue concerning `https`.

**Comment by DennisHeimbigner** [comment]
Found the problem; will have PR shortly.
