### ISSUE TITLE
ucar.nc2.filter.UnknownFilterException: Unknown filter - v5.6.0 

### ISSUE THREAD

**Issue by jacobwentzib** [Unidata/netcdf-java#1382]
### Versions impacted by the bug

5.6.0 - Latest

**Environment:**
**UCAR Library Version:** cdm-core 5.6.0
**Java Version:** 21 

### What went wrong?

Recently upgraded to 5.6.0 and see the following exception being thrown where the ServiceLoader is unable to load Filters properly. 

https://github.com/Unidata/netcdf-java/blob/42186c77b9d424aeb45e333be80593c7a03c608e/cdm/core/src/main/java/ucar/nc2/filter/Filters.java#L80

Once we downgrade back to _5.5.3_ everything works properly. 

Has there been any changes to classpath or anything else that could be causes this issue? We are seeing this isolated to jar executions but IDE development with target classes runs properly.

We have created a custom ServiceLoader within our application and can see the resources being found. 

### Relevant stack trace

Being invoked from: 
Variable.class:
```java
    public Array read(Section section) throws IOException, InvalidRangeException {
        return section == null ? this._read() : this._read(Section.fill(section, this.shape));
    }
```

Error throw from above link:
_java.io.IOException: ucar.nc2.filter.UnknownFilterException: Unknown filter: no filter found with id 2_

### If you have an example file that you can share, please attach it to this issue.
If so, may we include it in our test datasets to help ensure the bug does not return once fixed?
Note: the test datasets are publicly accessible without restriction.

Yes

### Code of Conduct

- [X] I agree to follow the UCAR/Unidata Code of Conduct

**Comment by tdrwenski** [comment]
- Can you add the full error stack trace?
- Are any FilterProviders getting loaded (yours or NetCDF-java's)? It looks like the error is about "id 2" which should be the `Shuffle` filter.

**Comment by jacobwentzib** [comment]
NetCDF-java's FilterProviders. 

Here is the full trace: 
java.io.IOException: ucar.nc2.filter.UnknownFilterException: Unknown filter: no filter found with id 2
        at ucar.nc2.internal.iosp.hdf5.H5tiledLayoutBB.<init>(H5tiledLayoutBB.java:90) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at ucar.nc2.internal.iosp.hdf5.H5iospNew.readData(H5iospNew.java:226) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at ucar.nc2.internal.iosp.hdf5.H5iospNew.readData(H5iospNew.java:204) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2122) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at ucar.nc2.Variable.reallyRead(Variable.java:797) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at ucar.nc2.Variable._read(Variable.java:736) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at ucar.nc2.Variable._read(Variable.java:754) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at ucar.nc2.Variable.read(Variable.java:600) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at <our>.GoesrDecoder.extractDataFromVariable(GoesrDecoder.java:376) ~[goesr-0.0.0.jar!/:0.0.0]
        at <our>.GoesrDecoder.extractDataAsync(GoesrDecoder.java:320) ~[goesr-0.0.0.jar!/:0.0.0]
        at <our>.GoesrDecoder.decode(GoesrDecoder.java:145) ~[goesr-0.0.0.jar!/:0.0.0]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354) ~[spring-aop-6.1.11.jar!/:6.1.11]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.11.jar!/:6.1.11]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.11.jar!/:6.1.11]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768) ~[spring-aop-6.1.11.jar!/:6.1.11]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:379) ~[spring-tx-6.1.11.jar!/:6.1.11]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.1.11.jar!/:6.1.11]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.11.jar!/:6.1.11]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768) ~[spring-aop-6.1.11.jar!/:6.1.11]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113) ~[spring-aop-6.1.11.jar!/:6.1.11]
        at org.springframework.util.concurrent.FutureUtils.lambda$toSupplier$0(FutureUtils.java:74) ~[spring-core-6.1.11.jar!/:6.1.11]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[na:na]
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:311) ~[na:na]
Caused by: ucar.nc2.filter.UnknownFilterException: Unknown filter: no filter found with id 2
        at ucar.nc2.filter.Filters.getFilter(Filters.java:80) ~[cdm-core-5.6.0.jar!/:5.6.0]
        at ucar.nc2.internal.iosp.hdf5.H5tiledLayoutBB.<init>(H5tiledLayoutBB.java:88) ~[cdm-core-5.6.0.jar!/:5.6.0]
        ... 24 common frames omitted

**Comment by tdrwenski** [comment]
Thanks for sending that. I am not aware of any changes between version 5.5.3 and 5.6.0 that may have caused this issue. And I am not yet able to reproduce this behavior. Just to be sure I am testing the same situation:
- is it correct you are using the artifact `cdm-core-5.6.0.jar`?
- Can you check that you have the netcdf-java filters in that jar? By doing e.g. `jar tf cdm-core-5.6.0.jar | grep META-INF/services/ucar.nc2.filter.FilterProvider`
- is your custom `Filter` implemented similar to the example [here](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/reading_zarr.html#filter-implementation) and registered via a `META-INF/services/ucar.nc2.filter.FilterProvider` file?

**Comment by jacobwentzib** [comment]
- Correct we are utilizing: cdm-core-5.6.0.jar
- Directory is Empty in META-INF/services for the dependency. 
- We do not have any custom Filter we are just trying to leverage existing.

**Comment by tdrwenski** [comment]
Thanks for checking that. I don't know how it's possible that your `cdm-core-5.6.0.jar` is missing those filters. Are you getting your artifacts from our artifacts server: https://artifacts.unidata.ucar.edu/repository/unidata-all/? Can you try replacing that dependency? For instance, by downloading it manually from [here](https://artifacts.unidata.ucar.edu/repository/unidata-all/edu/ucar/cdm-core/5.6.0/cdm-core-5.6.0.jar)?

**Comment by jacobwentzib** [comment]
the pom.xml:
```
  <properties>
    <edu.ucar.version>5.6.0</edu.ucar.version>
  </properties>
  
  ...
    <dependency>
      <groupId>edu.ucar</groupId>
      <artifactId>cdm-core</artifactId>
      <version>${edu.ucar.version}</version>
      <exclusions>
        <exclusion>
          <groupId>commons-logging</groupId>
          <artifactId>commons-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    ... 
      <repositories>
        <repository>
          <id>unidata-all</id>
          <name>Unidata All</name>
          <url>https://artifacts.unidata.ucar.edu/repository/unidata-all/</url>
        </repository>
        <repository>
          <id>ucar-unidata</id>
          <url>https://repo.osgeo.org/repository/release/</url>
        </repository>
      <repositories>
```

Expanding the jar I see the services in the META-INF of the cdm-core jar. 

It seems like the SPI is not working when bundled. As mentioned previously this works when ran in IDE with all jars on class path but when we create our jar it gets these issues where it cannot find the Filters. 

We do not want to shade our jar to navigate around this.

**Comment by jacobwentzib** [comment]
Bump on this.

**Comment by jacobwentzib** [comment]
Following up on this? Is there anything else we can do help get around this issue?

**Comment by tdrwenski** [comment]
Hi @jacobwentzib, sorry for the delay getting back to this.

I have looked at the cdm-core-5.5.3.jar and cdm-core-5.6.0.jar and see no differences with respect to the filter providers or class path. I have also tried using a jar execution of cdm-core-5.6.0.jar and am unable to reproduce your issue, the filters do get loaded.

Can you confirm there are no other environmental differences between your testing of 5.5.3 and 5.6.0? Can you also test with our 5.6.1-SNAPSHOT version?

**Comment by tdrwenski** [comment]
Not ideal, but maybe as a workaround, you can try copying [this](https://github.com/Unidata/netcdf-java/blob/maint-5.x/cdm/core/src/main/resources/META-INF/services/ucar.nc2.filter.FilterProvider) into your own `src/main/resources/META-INF/services/`

**Comment by Youdetsu** [comment]
I encountered the same issue in version 5.8.

**Comment by lesserwhirls** [comment]
How are you utilizing netCDF-Java? Are you using Maven, gradle, or something different? Are you creating an executable jar where you need to bundle dependencies?

**Comment by nicobrevin** [comment]
If your application is doing anything funky with class loaders (which mine was) you need to make sure the when the Filters class is loaded that the thread's context class loader is the same one that loads the Filter class.

For me, this reduces down to something like:

```java
Thread.currentThread().setContextClassLoader(specialClassLoader);
specialClassLoader.loadClass('ucar.nc2.filter.Filters')
```

Not sure if it's correct or not, as I am by no means a class loading expert, but the Filters class is creating a ServiceLoader without an explicit class loader, which defaults to using the context class loader.  

I wonder whether it would be safer for the code `ServiceLoader.load(FilterProvider.class))` to actually be `ServiceLoader.load(FilterProvider.class, Filters.class.getClassLoader()))` or maybe having some central place where it can be set during initialization? 

```java
public class UcarServiceLoader {
  // plus some methods to change this somewhere.  This could default to the context class loader, or could be null
  private static ClassLoader useClassLoader = Thread.currentThread().getContextClassLoader();
  
  public static <T> List<T> load(Class<T> serviceClass) {
    // here we could either default to using the context class loader (current behaviour), or `useClassLoader` or possibly 
    // serviceClass.getClassLoader()?
    ServiceLoader.load(serviceClass, useClassLoader)
  }
}
```

 As it stands, I can't be 100% sure that every netcdf class is being loaded while I've set the context class loader up, but I'm presuming that to be the case.

If nothing else, I hope this helps someone else that is hitting the same issue (possibly could be happening a lot in a webapp environment where classloaders are definitely funky)

**Comment by nicobrevin** [comment]
> As it stands, I can't be 100% sure that every netcdf class is being loaded while I've set the context class loader up, but I'm presuming that to be the case.

I've done some more testing and it's going to be very difficult to make sure the context class loader is set correctly for all the different ways the NetCDF library is using the ServiceLoader for its SPIs.  Some are using static initializers, which is fairly easy to fix, but some are loaded 'on-demand' which is much harder to control.

For my case, I'm only affected (I think) by the Filter SPI, which was easy enough to work around, but I can't say that'll always be the case.  Is there any interest in accepting a patch to be able to control the classloader that's being used by all those different calls to `ServiceLoader.load`?  Or maybe to change all the uses of it to consistently cache the services in a static initializer?

**Comment by lesserwhirls** [comment]
Greetings @nicobrevin! I think changing all the uses of `ServiceLoader.load` to consistently cache the services in a static initializer would be my preference, but I'm not sure if anyone using netCDF-Java is relying on the dynamic loading nature that some of those cases provide. I like the idea of having a central place to manage the classloader as you outlined above. Perhapse a first pass would be to work with the cases that already have a static initializer and see how that shapes up?

**Comment by nicobrevin** [comment]
Yeah OK, I'll try and knock up a patch for your perusal.

**Comment by nicobrevin** [comment]
@lesserwhirls - https://github.com/Unidata/netcdf-java/pull/1555 - this is what I was thinking.
