### ISSUE TITLE
Panoply experiences failed data requests, error messages from Apache httpclient library

### ISSUE THREAD

**Issue by ndp-opendap** [Unidata/netcdf-java#294]
**Panoply**
When Panoply is accessing data in NASA's NGAP cloud it is unable to retrieve the binary data from the server and the two different error dialogs appear to be from the Apache httpclient library.

<img width="539" alt="Panoply-Error-01" src="https://user-images.githubusercontent.com/8389499/82592664-1c268280-9b56-11ea-83ba-660f7d9d1783.png">

<img width="604" alt="Panoply-Error-02" src="https://user-images.githubusercontent.com/8389499/82592719-32344300-9b56-11ea-91ef-e5e887a7fbcf.png">

**ToolsUI**
Attempting to access the same dataset with ToolsUI (toolsUI-5.4.0-20200513.141840-35.jar) it produces this error:

```
org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:263)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:70)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at opendap.dap.DVector.deserialize(DVector.java:237)
	at opendap.dap.DataDDS.readData(DataDDS.java:136)
	at opendap.dap.DConnect2$DataDDSCommand.process(DConnect2.java:864)
	at opendap.dap.DConnect2.openConnection(DConnect2.java:309)
	at opendap.dap.DConnect2.getData(DConnect2.java:839)
	at opendap.dap.DConnect2.getData(DConnect2.java:902)
	at ucar.nc2.dods.DODSNetcdfFile.readDataDDSfromServer(DODSNetcdfFile.java:1478)
	at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1630)
	at ucar.nc2.Variable.reallyRead(Variable.java:794)
	at ucar.nc2.Variable._read(Variable.java:733)
	at ucar.nc2.Variable.read(Variable.java:611)
	at ucar.nc2.ui.op.DatasetViewer.showData(DatasetViewer.java:634)
	at ucar.nc2.ui.op.DatasetViewer.access$1200(DatasetViewer.java:56)
	at ucar.nc2.ui.op.DatasetViewer$NestedTable$3.actionPerformed(DatasetViewer.java:477)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
Other HTTP clients (cURL command line, etc) are able to make data requests to these servers and get back correct responses.

Has anyone seen this kind of thing?

Sincerely,

Nathan

**Comment by rschmunk** [comment]
@ndp-opendap, Could you remind me if we made enough progress on this (i.e., a newer Panoply using a newer NJ)  that this issue could be closed?

**Comment by ndp-opendap** [comment]
@rschmunk - I have not made no progress on this. So far Unidata hasn't responded directly to me or this ticket. Can they (or you) replicate the issue? I haven't looked more closely either as I have been pulled into other fires.

Do you have a thought about how we might proceed?

**Comment by lesserwhirls** [comment]
Hello @ndp-opendap - I'd be happy to take a look, although I have not seen this particular error myself. Do you have a URL I could use to try to reproduce the issue locally?

**Comment by ndp-opendap** [comment]
Greetings All,

After a lot of looking at the things I have determined that the source of this problems lies not in netcdf-java, Panoply, or even the Hyrax server, but rather a series of mysteriously bad things inside of AWS. A real lesson in the fragility of service chaining architectures.

I am going to close this so that you can all relax and take it easy from now on. ;)

Nathan
