### ISSUE TITLE
"IllegalStateException:  ObjectHeaderContinuation Missing signature" when trying to open GeoServer NetCDF response

### ISSUE THREAD

**Issue by EHJ-52n** [Unidata/netcdf-java#334]
> To report a non-security related issue, please provide:
> 
> * the version of the software with which you are encountering an issue
> * environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
> * a description of the issue with the steps needed to reproduce it
> 
> If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Used Versions**
  * cdm-core: 5.3.1
  * netcdf4: 5.3.1
  * both from ucar repositories

**Environmental Information**
  * os: Ubuntu 18.04.4 LTS
  * javac: openjdk 1.8.0_252
  * libnetcdf-dev: 4.6.0-2build1
  * libnetcdf13: 4.6.0-2build1
  * GeoServer:
    * Version: 2.6.12
    * host os: Debian GNU/Linux 9.5 (stretch)
      * netcdf-bin: 4.4.1.1-2
      * libnetcdf11: 4.4.1.1-2
    * java: Oracle Corporation: 1.8.0_252 (OpenJDK 64-Bit Server VM)
    * netcdf plugins:
      * NetCDF Coverage format (gs-netcdf) with GridCoverageMultiDimReader: 22.2
      * WCS NetCDF output Module (gs-netcdf-out) with GridCoverage2DWriter: 22.2

**Issue Description**

I want to request a one pixel time series from a GeoServer based WCS instance and process it. I receive the file and can write it to a temporary file and panoply is able to open it. When I try to open it via netcdf-java, I receive the following exception:

```

java.io.IOException: java.lang.IllegalStateException:  ObjectHeaderContinuation Missing signature
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:282)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:243)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:228)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:216)
[...]
Caused by: java.lang.IllegalStateException:  ObjectHeaderContinuation Missing signature
	at ucar.nc2.internal.iosp.hdf5.H5objects$DataObject.readMessagesVersion2(H5objects.java:524)
	at ucar.nc2.internal.iosp.hdf5.H5objects$DataObject.readMessagesVersion2(H5objects.java:527)
	at ucar.nc2.internal.iosp.hdf5.H5objects$DataObject.<init>(H5objects.java:374)
	at ucar.nc2.internal.iosp.hdf5.H5objects$DataObject.<init>(H5objects.java:234)
	at ucar.nc2.internal.iosp.hdf5.H5objects.readDataObject(H5objects.java:231)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.getDataObject(H5headerNew.java:2189)
	at ucar.nc2.internal.iosp.hdf5.H5objects$DataObjectFacade.<init>(H5objects.java:104)
	at ucar.nc2.internal.iosp.hdf5.H5objects.readGroupNew(H5objects.java:2147)
	at ucar.nc2.internal.iosp.hdf5.H5objects.access$700(H5objects.java:26)
	at ucar.nc2.internal.iosp.hdf5.H5objects$H5Group.<init>(H5objects.java:196)
	at ucar.nc2.internal.iosp.hdf5.H5objects$H5Group.<init>(H5objects.java:154)
	at ucar.nc2.internal.iosp.hdf5.H5objects.readRootSymbolTable(H5objects.java:58)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.readSuperBlock1(H5headerNew.java:350)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.read(H5headerNew.java:246)
	at ucar.nc2.internal.iosp.hdf5.H5iospNew.build(H5iospNew.java:119)
	at ucar.nc2.NetcdfFiles.build(NetcdfFiles.java:787)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:726)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:279)
	... 79 more
```

The causing line of code looks like the following:

```java
[...]
import ucar.nc2.dataset.NetcdfDataset;
import ucar.nc2.dataset.NetcdfDatasets;
[...]
NetcdfDataset netcdfDataset = NetcdfDatasets.openDataset(temp.getPath());
```

The temp file has the following type and size:
```
$ file /tmp/wcs-response-8305302443909512434.tmp 
/tmp/wcs-response-8305302443909512434.tmp: Hierarchical Data Format (version 5) data
$ stat /tmp/wcs-response-8305302443909512434.tmp
  File: /tmp/wcs-response-8305302443909512434.tmp
  Size: 12288     	Blocks: 24         IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 25705273    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/    eike)   Gid: ( 1000/    eike)
Access: 2020-06-19 12:08:21.586364273 +0200
Modify: 2020-06-19 12:08:18.338330669 +0200
Change: 2020-06-19 12:08:18.338330669 +0200
 Birth: -
```

I attached the file as zip: [wcs-response-8305302443909512434.zip](https://github.com/Unidata/netcdf-java/files/4804112/wcs-response-8305302443909512434.zip).

Is there any version mismatch that results in this error?

Do you need any additional information?

Because panoply can open the returned file of the GeoServer, I am not sure if this is an GeoServer or netcdf-java issue.

Thank you very much for your time!

**Comment by lesserwhirls** [comment]
If you are only trying to read the netCDF-4 file, you do not need the `netcdf4` artifact (you only need that if you are writing), unless you have configured netCDF-Java to read through the C library. I don't recommend that approach for reading unless its for debugging purposes.

When I try to use `h5dump` (v1.12.0) on the file, I get the following:

~~~
h5dump -H ./wcs-response-8305302443909512434.tmp
h5dump error: internal error (file h5dump.c:line 1578)
HDF5: infinite loop closing library
      L,T_top,P,P,FD,VL,VL,E,SL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL
~~~

I would expect that to work at the very least. If h5dump cannot read it, then it makes me think that the file is not a complete hdf5 file...maybe. It's possible that if I used the exact same version of HDF5 (with built with the same configuration options) as the one used by geoserver, I might be able to use `h5dump` successfully. According to the metadata in the file, it was written with netCDF-C 4.4.1.1 and HDF5 1.10.0.

**Comment by EHJ-52n** [comment]
The problem was in writing the GeoServer response to a temporary file. No problem in GeoServer or netcdf-java.
