### ISSUE TITLE
GribCollection fails in general case of CoordinateTime2D 

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#38]
This issue has been there forever, but the recent change of the default "ignore zero intervals" (was true, now false), has exposed the problem in one or more of our test datasets.

Reproduce by creating an ncx4 from cdmUnitTest/datasets/NDFD-CONUS-5km/.*grib2.

eg put the above expression in ToosUI,  IOSP/Grib2/Grib2Collection, then choose (rightmost icon) "Write Index", you will get:

GribCoverageDataset.open failed
java.lang.IllegalStateException: Time2D with type= MRC
	at ucar.nc2.grib.coverage.GribCoverageDataset.makeTime2DCoordinates(GribCoverageDataset.java:512)
	at ucar.nc2.grib.coverage.GribCoverageDataset.createCoverageCollection(GribCoverageDataset.java:180)
	at ucar.nc2.grib.coverage.GribCoverageDataset.open(GribCoverageDataset.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ucar.nc2.ft2.coverage.CoverageDatasetFactory.openGrib(CoverageDatasetFactory.java:113)
	at ucar.nc2.ft2.coverage.CoverageDatasetFactory.openCoverageDataset(CoverageDatasetFactory.java:61)

For NDFD thredds serving, can put the ""ignore zero intervals" back to true. But the general case should be fixed somehow.

**Comment by JohnLCaron** [comment]
MRC is working in ver8. Not sure what the status is in < ver8. Im going to close it.
