### ISSUE TITLE
unknown type=String thrown opening HDF-EOS file

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#455]
I am working with a recent 5.4 snapshot, but the problem described is found to first occur in a version of my software using a 5.3 snapshot from late February. Using software based on an earlier 5.3 snapshot, the problem does not occur. The problem is also seen using a toolsUI based on the 5.4 snapshot, but not the toolsUI 5.0 that I still have on hand.

A user has provided a couple HDF-EOS files which cannot be opened because `IospHelper.readData` is throwing an `IllegalStateException: unknown type= String`. The stack trace looks like

```
Caused by: java.lang.IllegalStateException: unknown type= String
	at ucar.nc2.iosp.IospHelper.readData(IospHelper.java:154)
	at ucar.nc2.iosp.IospHelper.readDataFill(IospHelper.java:58)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew$Vinfo.readString(H5headerNew.java:1939)
	at ucar.nc2.internal.iosp.hdf5.H5headerNew.readStructMetadata(H5headerNew.java:1591)
	at ucar.nc2.internal.iosp.hdf4.HdfEos.getStructMetadata(HdfEos.java:132)
	at ucar.nc2.internal.iosp.hdf4.HdfEos.amendFromODL(HdfEos.java:89)
	at ucar.nc2.internal.iosp.hdf5.H5iospNew.lambda$build$0(H5iospNew.java:125)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at ucar.nc2.internal.iosp.hdf5.H5iospNew.build(H5iospNew.java:123)
	at ucar.nc2.NetcdfFiles.build(NetcdfFiles.java:784)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:723)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:276)
	... 16 more
```

A sample dataset which demonstrates the problem can be [downloaded here](https://www.dropbox.com/s/aakmbm3jy9jpb26/VNP10A1_A2018001_h31v11_001_2019126193423_HEGOUT.nc?dl=0).

As noted above, this exception is thrown in software that uses an NJ snapshot from the end of February. However, it is not thrown in software using a snapshot dated January 30. Digging into the repo, I see that changes were committed to `H5headerNew` and `H5iospNew` three times between those dates. It looks like the `IospHelper` and `HdfEos` classes were not touched during that time.

**Comment by JohnLCaron** [comment]
Can this be closed?

**Comment by rschmunk** [comment]
@JohnLCaron, Probably so. I think @lesserwhirls's patch took care of the problem.
