### ISSUE TITLE
Processing openInMemory fails for non-filesystem datasets

### ISSUE THREAD

**Issue by brentlemons** [Unidata/netcdf-java#482]
version: 5.3.3
Java 11
linux and macos filesystems

Call in question:
`NetcdfFile ncf = NetcdfFiles.openInMemory("s3test", data);`

Exception:
```
No records found in dataset s3test: java.lang.IllegalStateException
java.lang.IllegalStateException: No records found in dataset s3test
	at ucar.nc2.grib.collection.Grib2CollectionBuilder.makeGroups(Grib2CollectionBuilder.java:139)
	at ucar.nc2.grib.collection.GribCollectionBuilder.createMultipleRuntimeCollections(GribCollectionBuilder.java:128)
	at ucar.nc2.grib.collection.GribCollectionBuilder.createIndex(GribCollectionBuilder.java:120)
	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromDataFile(GribCdmIndex.java:830)
	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromDataFile(GribCdmIndex.java:807)
	at ucar.nc2.grib.collection.GribCdmIndex.openGribCollectionFromRaf(GribCdmIndex.java:777)
	at ucar.nc2.grib.collection.GribIosp.build(GribIosp.java:148)
	at ucar.nc2.NetcdfFiles.build(NetcdfFiles.java:787)
	at ucar.nc2.NetcdfFiles.open(NetcdfFiles.java:726)
	at ucar.nc2.NetcdfFiles.openInMemory(NetcdfFiles.java:674)
	at com.stuff.noaa.hrrr.HRRRParseFunctionHandler.handleRequest(HRRRParseFunctionHandler.java:122)
	at com.stuff.noaa.hrrr.HRRRParseFunctionHandler.handleRequest(HRRRParseFunctionHandler.java:68)

```
openInMemory creates an [InMemoryRandomAccessFile](https://github.com/Unidata/netcdf-java/blob/fa73b22e7fffcda171844a32390051b18f01acfe/cdm/core/src/main/java/ucar/nc2/NetcdfFiles.java#L633). The [filename](https://github.com/Unidata/netcdf-java/blob/fa73b22e7fffcda171844a32390051b18f01acfe/cdm/core/src/main/java/ucar/unidata/io/InMemoryRandomAccessFile.java#L27) property in the InMemoryRandomAccessFile is set to the name of the dataset. When passing a byte array, this does not represent a file on the filesystem.

The raf is passed to openGribCollectionFromRaf(...). From there it is passed to [openGribCollectionFromDataFile(...)](https://github.com/Unidata/netcdf-java/blob/5fd9cadfa8f5f1b607b39db3a41b40ce83d2a41e/grib/src/main/java/ucar/nc2/grib/collection/GribCdmIndex.java#L799). Within this method, the following occurs:

```
String filename = dataRaf.getLocation();
File dataFile = new File(filename);

MFile mfile = new MFileOS(dataFile);
return openGribCollectionFromDataFile(isGrib1, mfile, updateType, config, errlog, logger);

```

dataRaf.getLocation() only points to a made up name, therefore there is no file to open. As soon as it tries to use the "file", it exceptions out with the above error.

This occurs with openInMemory using [byte[]](https://github.com/Unidata/netcdf-java/blob/fa73b22e7fffcda171844a32390051b18f01acfe/cdm/core/src/main/java/ucar/nc2/NetcdfFiles.java#L632) as well as [URI](https://github.com/Unidata/netcdf-java/blob/fa73b22e7fffcda171844a32390051b18f01acfe/cdm/core/src/main/java/ucar/nc2/NetcdfFiles.java#L615). It doesn't happen when you openInMemory with a [filename](https://github.com/Unidata/netcdf-java/blob/fa73b22e7fffcda171844a32390051b18f01acfe/cdm/core/src/main/java/ucar/nc2/NetcdfFiles.java#L599) because it is later able to open the file. However, that means it is actually loading the file into memory, or randomly accessing later, the same file/data.

**Comment by JohnLCaron** [comment]
What is in the data array?

The problem with GRIB is that it needs the GRIB index (gbx9) file in addition to the binary GRIB file. So there would have to be a special API for that, telling it to put the gbx file into memory also I suppose.

**Comment by JohnLCaron** [comment]
See Issue #638
