### ISSUE TITLE
Failure to write netcdf file using ToolsUI

### ISSUE THREAD

**Issue by sgdecker** [Unidata/netcdf-java#643]
I start up the UI with:
`java -Xmx1g -jar toolsUI-5.4.1.jar `

I open a recent Level 2 NEXRAD file. So far so good aside from this warning:
`Unknown radial product dbp8=8060 tname=CFP (this is the only message you will see about this.)`

I attempt to write to netcdf, using all defaults.

This error appears:
`
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: ucar.nc2.NetcdfFileWriter$Version cannot be cast to ucar.nc2.write.NetcdfFileFormat
	at ucar.nc2.ui.dialog.NetcdfOutputChooser.okButtonActionPerformed(NetcdfOutputChooser.java:74)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

I know nothing about Java, so I may be doing something wrong.

This is on Linux (RHEL 7). java -version reports:
`
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
`

**Comment by lesserwhirls** [comment]
You are not doing anything wrong, this is indeed a bug - thank you for the report! While I work on a fix, is your ultimate end goal to get the level 2 file into a netCDF file?

**Comment by sgdecker** [comment]
Yes, I was looking for a quick and dirty way to generate a netCDF file of level 2 radar data. The first Google hit when I looked at how to do this was (website down, so here is the cached version):
https://webcache.googleusercontent.com/search?q=cache:odfqB3nAryYJ:https://www.ncdc.noaa.gov/data-access/radar-data/radar-decoding+&cd=1&hl=en&ct=clnk&gl=us&client=firefox-b-1-e
which led me to the ToolsUI approach.

**Comment by lesserwhirls** [comment]
Ok, cool. So there is a relatively straightforward way to do the conversion from the command line using the Java version of [Nccopy](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/cdm_utility_programs.html#nccopy), which bypasses the need to do use the toolsUI GUI. You will need Java 8 or greater (I used 11). Also, you will need the netCDF-C library installed, as you will need to be able to write netCDF-4 files and we do not do that using native Java.

The command will look like this:

~~~sh
java -classpath ./netcdfAll-5.4.1.jar ucar.nc2.write.Nccopy -f netcdf4 -i file.ar2v -o .file.nc4
~~~

The `netcdfAll-5.4.1.jar` file can be downloaded [here](https://www.unidata.ucar.edu/downloads/netcdf-java/).

If the netCDF-C library isn't on your system path, you will need to tell Java where to find the library files using a property flag. The location you will need to know is where:
 * Linux: the `.so` files live
 * Mac: the `.dylib` files live
 * Windows: the `.dll` files live

Once you have that location, you can use the `-Djna.library.path=` flag like so:

~~~sh
java -Djna.library.path=/path/to/nc-c/lib/ -classpath ./netcdfAll-5.4.1.jar ucar.nc2.write.Nccopy -f netcdf4 -i ./file.ar2v -o ./file.nc4
~~~

(note: on windows in PowerShell, you would need to use quotes around part of the -D flag, like this: `-D"jna.library.path"=/path/to/nc-c/lib/`).

Also, it might be helpful to know that if you are downloading the file first and are only interested in converting to netCDF, then you can put the http address directly in the `Nccopy` command above and skip the downloading step, so something like:

~~~sh
java -classpath ./netcdfAll-5.4.1.jar ucar.nc2.write.Nccopy -f netcdf4 -i https://server.com/data/file.ar2v -o .file.nc4
~~~

**Comment by sgdecker** [comment]
Thanks, the command-line approach works perfectly!
