### ISSUE TITLE
Support GRIB2 DRS 42

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#753]
This seems to be a problem with 5.4-MAINT up to the current (7?) development branch.

A user sent me a GRIB2 file that netCDF-Java will open, but when one then tries to extract a variable, an "Unsupported DRS type = 42" exception is thrown by the `Grib2DataReader.factory` method. (But note that the same exception could be thrown by `Grib2DataReader.getData`.)

Comparison of the switch statements in these methods to ECMWF's [data representation template list](https://apps.ecmwf.int/codes/grib/format/grib2/ctables/5/0), several such templates are not handled. But for the moment, 42 is the one of concern.

A stack trace is appended (using 5.4-MAINT), but note that the line numbers in `Grib2Drs` and `Grib2DataReader` are slightly off as I inserted some logging.

A sample file that demonstrates the problem is [here on Dropbox](https://www.dropbox.com/s/i40oadlwh8lakgc/fc2021070509%2B001.grib2?dl=0).

The user also comments that: "As far as I have understood, this file has been generated by using ECMWF's ECCODES library and it originates from MetCoOp (251) center."

--
```
java.lang.RuntimeException: Unsupported DRS type = 42
	at ucar.nc2.grib.grib2.Grib2Drs.factory(Grib2Drs.java:39)
	at ucar.nc2.grib.grib2.Grib2SectionDataRepresentation.getDrs(Grib2SectionDataRepresentation.java:83)
	at ucar.nc2.grib.grib2.Grib2Record.readData(Grib2Record.java:319)
	at ucar.nc2.grib.collection.GribDataReader$Grib2DataReader.readData(GribDataReader.java:474)
	at ucar.nc2.grib.collection.GribDataReader.read(GribDataReader.java:273)
	at ucar.nc2.grib.collection.GribDataReader.readDataFromCollection(GribDataReader.java:116)
	at ucar.nc2.grib.collection.GribDataReader.readData(GribDataReader.java:81)
	at ucar.nc2.grib.collection.GribIosp.readData(GribIosp.java:1085)
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2122)
	at ucar.nc2.Variable.reallyRead(Variable.java:797)
	at ucar.nc2.Variable._read(Variable.java:736)
	at ucar.nc2.Variable.read(Variable.java:614)
	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:459)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:432)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:442)
	at ucar.nc2.Variable.read(Variable.java:600)
	at ucar.nc2.Variable.read(Variable.java:546)
	at gov.nasa.giss.data.nc.array.NcArray2D.doSlice(NcArray2D.java:363)
...
```

**Comment by rschmunk** [comment]
Also, it seems that this issue involves use of a Lambert Conformal Conic projected grid.

Note that I posted an issue two years ago involving use of a Lambert Azimuthal Equal Area projected grid, although that manifested as an inability to even open the dataset. See #22.

**Comment by lesserwhirls** [comment]
>Comparison of the switch statements in these methods to ECMWF's data representation template list, several such templates are not handled. But for the moment, 42 is the one of concern.

Usually a DRS isn't implemented due to lack of a sample file. That said, DRS 42 looks to be pretty complicated:

https://library.wmo.int/doc_num.php?explnum_id=10722 (pdf page 132)

Let me see if there is a java port of `libaec` out there that we could use. Otherwise, we'd either have to write our own implementation or start wrapping more C code, neither of which sound like great options.

**Comment by rschmunk** [comment]
Oh, ugh, a compression scheme.

**Comment by rschmunk** [comment]
Oh, ugh. Looking at that PDF page. 😱

**Comment by rschmunk** [comment]
Ping! I just had another request for DRS 42 from a developer at ECMWF.

**Comment by shahramn** [comment]
Thanks for chasing this up. From cycle 48R1 ECMWF data by default will use CCSDS packing ( for gridded fields )

**Comment by rschmunk** [comment]
Ping! I just had yet another query about DRS 42 from someone trying to work with ECMWF data.

**Comment by haileyajohnson** [comment]
@rschmunk it would be great to have this, but unfortunately our dev teams hands are really full right now, so unless we get some outside help on this issue, it's not going to make it to the top of the TODO list for a while.

**Comment by rschmunk** [comment]
Unfortunately, as @lesserwhirls pointed out, this one looks like a hairball.

Maybe some ECMWF person will get attached to the issue and write some code?

**Comment by Yaqiang** [comment]
GRIB2 DRS 42 support request + 1.

**Comment by NZTSL** [comment]
Another GRIB2 DRS 42 support request here, thanks.

**Comment by rschmunk** [comment]
@haileyajohnson, I hate to say it but I just heard from another user whose ability to view ECMWF data has been crippled because ECMWF is now shipping the product using data representation 42.

Edit: This looks like the same or related product as what @shahramn mentioned on Feb. 20.

**Comment by haileyajohnson** [comment]
So I 100% hear that this is becoming a major issue. The problems we previously listed though still remain. I think this is going to involve us doing some major work on compression in general in netcdf-java, which wouldn't be the worst thing. I don't know how long it would take to plan/design/develop though, so I guess my question is what is the impact to everyone +1ing this issue if it takes 3/6/9 months before we're able to ship this as a feature?

**Comment by cvasquez-github** [comment]
GRIB2 DRS 42 support request + 1

**Comment by shahramn** [comment]
You could always convert the CCSDS GRIB ( gridded ) fields back to Simple Packing. E.g.,
via the ecCodes grib_set command-line tool
```
grib_set -r -w packingType=grid_ccsds -s packingType=grid_simple ccsds.grib grid_simple.grib
```

Of course it would be fantastic if Panoply could decode such GRIBs but this is a temporary solution

**Comment by JohnLCaron** [comment]
Ive been using https://openjdk.org/jeps/434 "JEP 434: Foreign Function &
Memory API" in Java 20, and it works well and seems to solve most of the
problems with jni/jna. One could use it to wrap libaec.

**Comment by shahramn** [comment]
Dear John,
That would be fantastic! I'll buy you a beer if you do it ;)

**Comment by haileyajohnson** [comment]
That's kinda the direction we're leaning, but currently netcdf-java is committed to supporting jdk-8. What we're considering is putting new features that require higher java versions in a different subproject, and encouraging people to use a later java version to get those features.

**Comment by rongmafight** [comment]
GRIB2 DRS 42 support request + 1

**Comment by JohnLCaron** [comment]
Seems like for some, compiling libaec and running Java 20 might be worth it for getting access to DRS 42 from netcdf-java. What do you think, @DennisHeimbigner ? Im not seeing any java ports available.

**Comment by DennisHeimbigner** [comment]
According to this page: https://gitlab.dkrz.de/k202009/libaec,
it is a an implementation of the Golomb-Rice algorithm.
So I went looking for Golomb-Rice in Java an found this site:
https://github.com/tomgibara/coding/blob/master/src/main/java/com/tomgibara/coding/GolombCoding.java

So, it is barely possible that this could replace libaec.

**Comment by dpoutier** [comment]
Hello,
Is there an update about the issue "Unsupported DRS type = 42"?
it seems that this issue is thrown with Meteo France Grib file. "erreur generale = java.lang.UnsupportedOperationException: Unsupported DRS type = 42"

Thanks in advance.

**Comment by lesserwhirls** [comment]
Hello all! While I don't have a concrete timeline for this yet, the plan is to add hooks to use native libaec. As part of this, we will likely begin shipping (optional) 'native' jars for the most popular platforms as a way of trying to ease the pain of dealing with native code.

**Comment by rschmunk** [comment]
@lesserwhirls, Does this mean that the native libaec binary would be included in the netcdfAll jar?

I think that would work with Panoply, although I might have to update my build process a smidge in order to deal with macOS notarization issues (once you figure them out, they'll change again in 9 months).

**Comment by dpoutier** [comment]
@lesserwhirls Thanks for fast response. 

I have some information about new Meteo France grib files. 
It seems that Meteo France ("The french NOAA") use a packed format "CCSDS" for the new grib files AROME and ARPEGE (Meterologic datas) . Therefore netcdf issue "Unsupported DRS type = 42" when i try to open file with netcdf java library.

According to MeteoFrance's advice,  i have converted New Grib file to a grib file (with ECMWF Grib Tools) without packed format and tested it. And it's OK. netcdf-java can open and read datas without "Unsupported DRS type = 42" issue.

But it's not usefull if we need to convert each file with ECMWF Grib Tools (on linux or with python script, for infomration we are full Microsoft Windows). And it will become a nightmare to maintain such a production chain.

The best thing would be to add GRIB2 DRS 42 support 

Best regards.

**Comment by dpoutier** [comment]
@rschmunk Hello
I have tested new grib file compressed (CCSDS) with Panoply 5.5.5. And i have the same issue.

![Image](https://github.com/user-attachments/assets/161bdfca-24c8-4111-895a-5ead58047b2d)


Best regards.

**Comment by lesserwhirls** [comment]
> [@lesserwhirls](https://github.com/lesserwhirls), Does this mean that the native libaec binary would be included in the netcdfAll jar?
> 
> I think that would work with Panoply, although I might have to update my build process a smidge in order to deal with macOS notarization issues (once you figure them out, they'll change again in 9 months).

I have not decided if jars containing native libraries would be included in the netcdfAll jar or if they would be separate and used in addition to netCDFAll. At this point I am leaning towards at least having distinct jar files for the three major platforms (windows, linux, macOS), noting that some platforms might have multiple jars for different architectures. There is the possibility of creating a jar that contains all, and that could go into something like the netCDFAll jar, but I think having multiple jars will be the minimum. My thoughts, uninformed by actual experience, is that If the native libraries are in separate jar files, that might help ease the inclusion in projects with installers for different platforms? As examples, I don't know what signing for the mac looks like if `x86_64` and `.dll` files show up in the distributed files, or if a single installer can include binaries for intel and arm macs. Whatever the case may be, I'd like to make the distribution of native binaries as user friendly as possible, and that includes those like yourself who have to deal with signing headaches and heartaches. You opinions on this are highly valued!

**Comment by lesserwhirls** [comment]
> [@lesserwhirls](https://github.com/lesserwhirls) Thanks for fast response.
> 
> I have some information about new Meteo France grib files. It seems that Meteo France ("The french NOAA") use a packed format "CCSDS" for the new grib files AROME and ARPEGE (Meterologic datas) . Therefore netcdf issue "Unsupported DRS type = 42" when i try to open file with netcdf java library.
> 
> According to MeteoFrance's advice, i have converted New Grib file to a grib file (with ECMWF Grib Tools) without packed format and tested it. And it's OK. netcdf-java can open and read datas without "Unsupported DRS type = 42" issue.
> 
> But it's not usefull if we need to convert each file with ECMWF Grib Tools (on linux or with python script, for infomration we are full Microsoft Windows). And it will become a nightmare to maintain such a production chain.
> 
> The best thing would be to add GRIB2 DRS 42 support
> 
> Best regards.

I completely understand the inconvenience of needing to convert in order to have netCDF-Java support. libaec supports CCSDS, so once this is working, you will not need to convert, even on windows :-)

**Comment by rschmunk** [comment]
@lesserwhirls, What I'm chiefly concerned about is that the user not have to have installed other stuff. For example, netCDF-Java has hooks to interact with an installed netCDF-C library, which personally I've never managed to do. And a lot of my users are students with limited tech experience, so it can be tough enough explaining to them how to deal with basic Java issues.

Anyhow, there are already a couple native Darwin binaries in the netcdfAll jar, and they occasionally give me fits as far as macOS codesigning and notarization is concerned because Apple tweaks things now and then, most recently AFAIK the first of this past September. My history of dealing with that and my current workaround is detailed in issue #199.

So if Unidata opts to include more native code in the distro, I can deal with an additional jar or two. As long as I know that when codesigning my macOS release suddenly fails, at least I have an idea what to look for.

Edit: The above being said, having to deal with different jars of add'l code for different OSes could make my build process a little more... complicated.

**Comment by Armin-RS** [comment]
ECMWF is planning to use CCSDS compression for most (if not all) their GRIB2 model data in the future (see their recent webinar https://www.youtube.com/watch?v=uR3ZN9ANczg).

Also Deutscher Wetterdienst (DWD) in Germany is planning to use more CCSDS compression for DWD GRIB2 model data.

And the Unidata netCDF-Java library is used by many hydrological agencies in Germany which are using DWD and ECMWF forecasts for their hydrological forecast. 

So it would be really great, if you could support CCSDS in the near future. Thanks a lot for your work in this direction!

**Comment by YeYongFen** [comment]
you can use wgrib tool ，transfer grib2 to netcdf ,

 `wgrib2 ../example/eta.t00z.awphys18.grb2 -netcdf eta.nc`

you can download the   wgrib2 （ window ）here  
https://gitcode.com/open-source-toolkit/fd532/blob/main/wgrip.zip 

![Image](https://github.com/user-attachments/assets/00c4dab2-d071-4d69-93a6-fd1f88cf64c9)

**Comment by lesserwhirls** [comment]
Just a quick update on this issue - I have a local branch with native libaes wrapped using JNA and can do round trip encoding/decoding, as well as support for handling the native libraries distributed within a jar file (so a path for users that avoids needing to manually install extra libraries on their system). I need to implement DRS 42 within our grib code using the wrapper to make things fully functional, but it's almost there.

**Comment by lesserwhirls** [comment]
Ok, with PR Unidata/netcdf-java#1426 in, I'm ready to tackle the GRIB specific code for implementing DRS 42 (_this should be the easy part, he whispers in fear_). I don't have a good sample on hand at the moment, but will dig around for one tomorrow...unless someone has a small sample message that they would be willing to share that could be used in unit/integration tests (so, a file that can be publicly distributed without restrictions).

**Comment by Armin-RS** [comment]
Hi @lesserwhirls, I've attached a file from the German Meteorological Service's (DWD) OpenData server (zipped only for Github):
https://opendata.dwd.de/weather/nwp/icon-eu/grib/12/t_2m/

It is 2m temperature for a 12 UTC model run of the DWD ICON-EU (Europe) model at forecast time +14h.

I then used ECMWF's ecCodes library to convert the GRIB2 file to CCSDS compression:
[icon-eu_europe_regular-lat-lon_single-level_2025031912_014_T_2M_CCSDS.grib2.zip](https://github.com/user-attachments/files/19360481/icon-eu_europe_regular-lat-lon_single-level_2025031912_014_T_2M_CCSDS.grib2.zip)

Is that helpful for you ?

**Comment by lesserwhirls** [comment]
@Armin-RS - that will work great - thank you!

**Comment by shahramn** [comment]
Re: using ecCodes to convert from Simple Packing to CCSDS
See
https://confluence.ecmwf.int/pages/viewpage.action?pageId=146658047

**Comment by lesserwhirls** [comment]
@Armin-RS, how does this look?

![Image](https://github.com/user-attachments/assets/fbf68e6c-9a80-4eca-8587-873f52cddd17)

Seems to compare well with the stats output from ecCodes `grib_dump`.

**Comment by Armin-RS** [comment]
@lesserwhirls this looks really good! 

Thank's a lot for including CCSDS compression into the library! 
This will make many people in the flood forecasting community in Germany very happy who are using this library via different software packages.

Can you tell me in which library version this capability will be released to the public ?

**Comment by lesserwhirls** [comment]
I plan on putting up a PR for this early next week (just need to finish up the documentation). This will be part of the next release (v5.8.0), -SNAPSHOTS of which will start being produced after the PR is merged.

**Comment by lesserwhirls** [comment]
Alright, that should do it. If you have libaec installed on your system and it is in one of the system library paths, `5.8.0-SNAPSHOT` of the `edu.ucar:grib` should find it and work without adding any additional artifacts to your build. If libaec isn't installed, but you are on x86-64 Windows, Mac, or Linux, or aarch64 Mac or Linux, you can add the new artifact `edu.ucar:libaec-native:5.8.0-SNAPSHOT` and the appropriate library shipped within that jar file will be used. If you have libaec installed and you include the new `edu.ucar:libaec-native:5.8.0-SNAPSHOT` artifact, an appropriate library from the jar will be preferred, if found, otherwise the system provided library will be used. If neither of these are true, you will get an error when trying to read data from the GRIB message.

**Comment by rschmunk** [comment]
> If you have _xxx_ installed on your system …

Seeing this at 3:30 a.m., and my mind is melting.

Maybe things will make more sense after the sun comes up.

**Comment by Yaqiang** [comment]
> Alright, that should do it. If you have libaec installed on your system and it is in one of the system library paths, `5.8.0-SNAPSHOT` of the `edu.ucar:grib` should find it and work without adding any additional artifacts to your build. If libaec isn't installed, but you are on x86-64 Windows, Mac, or Linux, or aarch64 Mac or Linux, you can add the new artifact `edu.ucar:libaec-native:5.8.0-SNAPSHOT` and the appropriate library shipped within that jar file will be used. If you have libaec installed and you include the new `edu.ucar:libaec-native:5.8.0-SNAPSHOT` artifact, an appropriate library from the jar will be preferred, if found, otherwise the system provided library will be used. If neither of these are true, you will get an error when trying to read data from the GRIB message.

Great improvement! I also ever considered to do similar wrap using JavaCPP, but it is still just thinking. It's good feeling to use your working effort to read CCSDS compression GRIB data. Thank a lot!

I just updated MeteoInfo to version 4.0 which using netCDF-Java 5.8.0-SNAPSHOT for CCSDS compression GRIB data support.

![Image](https://github.com/user-attachments/assets/7934ab73-8d80-41a2-bb17-91b9b26ac2c8)

**Comment by lesserwhirls** [comment]
> > If you have _xxx_ installed on your system …
> 
> Seeing this at 3:30 a.m., and my mind is melting.
> 
> Maybe things will make more sense after the sun comes up.

I think what you will want to do for Panoply is bump netCDF-Java to 5.8.0-SNAPSHOT and add the new native-libaec jar. Then users will not need to build or install and c libraries.

**Comment by lesserwhirls** [comment]
> > Alright, that should do it. If you have ...
> 
> Great improvement! I also ever considered to do similar wrap using JavaCPP, but it is still just thinking. It's good feeling to use your working effort to read CCSDS compression GRIB data. Thank a lot!
> 
> I just updated MeteoInfo to version 4.0 which using netCDF-Java 5.8.0-SNAPSHOT for CCSDS compression GRIB data support.
> 
> ![Image](https://github.com/user-attachments/assets/7934ab73-8d80-41a2-bb17-91b9b26ac2c8)

This looks great!

**Comment by rschmunk** [comment]
> I think what you will want to do for Panoply is bump netCDF-Java to 5.8.0-SNAPSHOT and add the new native-libaec jar. Then users will not need to build or install and c libraries.

Still haven't looked at this yet today, but is there something I need to add to my build chain to create the jar? Some additional Gradle command?

**Comment by rschmunk** [comment]
Okay, it seems that I don't actually have to add another jar to my package, so don't need to figure out how to create it. Instead I added

`  netcdfAll project(':native-compression:libaec-native')`

to the fatjars dependencies for building netcdfAll, and the necessary code was bundled into netcdfAll-5.8.0-SNAPSHOT.

But… as I anticipated, the macOS version of Panoply then fails to notarize because the two libaec dylib's for Darwin are not codesigned. That meant adding a couple more commands to my build script for netcdfAll as mentioned above (2024/11/13) and more fully described at #199.

Anyhow, it seems my development copy of Panoply can now plot data using DRS42. I grabbed example [ECMWF forecast](https://data.ecmwf.int/forecasts/) GRIB2 files and voila. A copy of Panoply from a month ago would just puke the DRS42 error when encountering these.

![Image](https://github.com/user-attachments/assets/e41cc1e9-caf9-4dec-9363-0534d3844741)

**Comment by rschmunk** [comment]
Oh, hey. Found the dataset that originally prompted me to file this issue and success plotting from there also. As noted waaaay back at the top of this, the data are on a Lambert Conformal Conic grid.

![Image](https://github.com/user-attachments/assets/04060024-899f-4c5c-b471-ec5448f4b03b)

**Comment by lesserwhirls** [comment]
Great news @rschmunk! I mean, aside from the code signing headaches, and that it took several years to get into place :-/
